package com.dzx.app.entity;

public class Author {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column author.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column author.username
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column author.password
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column author.email
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column author.favourite_section
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private String favouriteSection;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column author.bio
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private String bio;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column author.id
	 * @return  the value of author.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column author.id
	 * @param id  the value for author.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column author.username
	 * @return  the value of author.username
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column author.username
	 * @param username  the value for author.username
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column author.password
	 * @return  the value of author.password
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column author.password
	 * @param password  the value for author.password
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column author.email
	 * @return  the value of author.email
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column author.email
	 * @param email  the value for author.email
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column author.favourite_section
	 * @return  the value of author.favourite_section
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public String getFavouriteSection() {
		return favouriteSection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column author.favourite_section
	 * @param favouriteSection  the value for author.favourite_section
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setFavouriteSection(String favouriteSection) {
		this.favouriteSection = favouriteSection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column author.bio
	 * @return  the value of author.bio
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public String getBio() {
		return bio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column author.bio
	 * @param bio  the value for author.bio
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setBio(String bio) {
		this.bio = bio;
	}
}