package com.dzx.app.entity;

public class Comment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.post_id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private Integer postId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.name
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.comment
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private String comment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.id
	 * @return  the value of comment.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.id
	 * @param id  the value for comment.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.post_id
	 * @return  the value of comment.post_id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public Integer getPostId() {
		return postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.post_id
	 * @param postId  the value for comment.post_id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setPostId(Integer postId) {
		this.postId = postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.name
	 * @return  the value of comment.name
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.name
	 * @param name  the value for comment.name
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.comment
	 * @return  the value of comment.comment
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.comment
	 * @param comment  the value for comment.comment
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
}