package com.dzx.app.entity;

public class Node {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column node.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column node.parent_id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private Integer parentId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column node.id
	 * @return  the value of node.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column node.id
	 * @param id  the value for node.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column node.parent_id
	 * @return  the value of node.parent_id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column node.parent_id
	 * @param parentId  the value for node.parent_id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}
}