package com.dzx.app.entity;

import java.util.Date;
import java.util.List;

public class Post {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.blog_id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private Integer blogId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.author_id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private Integer authorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.created_on
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private Date createdOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.section
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private String section;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.subject
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private String subject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.draft
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private Integer draft;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.body
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private String body;
	
	private Author author;
	
	private List<Comment> comments;
	
	private List<Tag> tags;
	

	public Author getAuthor() {
		return author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	public List<Comment> getComments() {
		return comments;
	}

	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}

	public List<Tag> getTags() {
		return tags;
	}

	public void setTags(List<Tag> tags) {
		this.tags = tags;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.id
	 * @return  the value of post.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.id
	 * @param id  the value for post.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.blog_id
	 * @return  the value of post.blog_id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public Integer getBlogId() {
		return blogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.blog_id
	 * @param blogId  the value for post.blog_id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setBlogId(Integer blogId) {
		this.blogId = blogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.author_id
	 * @return  the value of post.author_id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public Integer getAuthorId() {
		return authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.author_id
	 * @param authorId  the value for post.author_id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.created_on
	 * @return  the value of post.created_on
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public Date getCreatedOn() {
		return createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.created_on
	 * @param createdOn  the value for post.created_on
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.section
	 * @return  the value of post.section
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public String getSection() {
		return section;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.section
	 * @param section  the value for post.section
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setSection(String section) {
		this.section = section;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.subject
	 * @return  the value of post.subject
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.subject
	 * @param subject  the value for post.subject
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.draft
	 * @return  the value of post.draft
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public Integer getDraft() {
		return draft;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.draft
	 * @param draft  the value for post.draft
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setDraft(Integer draft) {
		this.draft = draft;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.body
	 * @return  the value of post.body
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public String getBody() {
		return body;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.body
	 * @param body  the value for post.body
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setBody(String body) {
		this.body = body;
	}
}