package com.dzx.app.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PostExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public PostExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andBlogIdIsNull() {
			addCriterion("blog_id is null");
			return (Criteria) this;
		}

		public Criteria andBlogIdIsNotNull() {
			addCriterion("blog_id is not null");
			return (Criteria) this;
		}

		public Criteria andBlogIdEqualTo(Integer value) {
			addCriterion("blog_id =", value, "blogId");
			return (Criteria) this;
		}

		public Criteria andBlogIdNotEqualTo(Integer value) {
			addCriterion("blog_id <>", value, "blogId");
			return (Criteria) this;
		}

		public Criteria andBlogIdGreaterThan(Integer value) {
			addCriterion("blog_id >", value, "blogId");
			return (Criteria) this;
		}

		public Criteria andBlogIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("blog_id >=", value, "blogId");
			return (Criteria) this;
		}

		public Criteria andBlogIdLessThan(Integer value) {
			addCriterion("blog_id <", value, "blogId");
			return (Criteria) this;
		}

		public Criteria andBlogIdLessThanOrEqualTo(Integer value) {
			addCriterion("blog_id <=", value, "blogId");
			return (Criteria) this;
		}

		public Criteria andBlogIdIn(List<Integer> values) {
			addCriterion("blog_id in", values, "blogId");
			return (Criteria) this;
		}

		public Criteria andBlogIdNotIn(List<Integer> values) {
			addCriterion("blog_id not in", values, "blogId");
			return (Criteria) this;
		}

		public Criteria andBlogIdBetween(Integer value1, Integer value2) {
			addCriterion("blog_id between", value1, value2, "blogId");
			return (Criteria) this;
		}

		public Criteria andBlogIdNotBetween(Integer value1, Integer value2) {
			addCriterion("blog_id not between", value1, value2, "blogId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdIsNull() {
			addCriterion("author_id is null");
			return (Criteria) this;
		}

		public Criteria andAuthorIdIsNotNull() {
			addCriterion("author_id is not null");
			return (Criteria) this;
		}

		public Criteria andAuthorIdEqualTo(Integer value) {
			addCriterion("author_id =", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdNotEqualTo(Integer value) {
			addCriterion("author_id <>", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdGreaterThan(Integer value) {
			addCriterion("author_id >", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("author_id >=", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdLessThan(Integer value) {
			addCriterion("author_id <", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdLessThanOrEqualTo(Integer value) {
			addCriterion("author_id <=", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdIn(List<Integer> values) {
			addCriterion("author_id in", values, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdNotIn(List<Integer> values) {
			addCriterion("author_id not in", values, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdBetween(Integer value1, Integer value2) {
			addCriterion("author_id between", value1, value2, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdNotBetween(Integer value1, Integer value2) {
			addCriterion("author_id not between", value1, value2, "authorId");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNull() {
			addCriterion("created_on is null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNotNull() {
			addCriterion("created_on is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnEqualTo(Date value) {
			addCriterion("created_on =", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotEqualTo(Date value) {
			addCriterion("created_on <>", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThan(Date value) {
			addCriterion("created_on >", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThanOrEqualTo(Date value) {
			addCriterion("created_on >=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThan(Date value) {
			addCriterion("created_on <", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThanOrEqualTo(Date value) {
			addCriterion("created_on <=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIn(List<Date> values) {
			addCriterion("created_on in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotIn(List<Date> values) {
			addCriterion("created_on not in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnBetween(Date value1, Date value2) {
			addCriterion("created_on between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotBetween(Date value1, Date value2) {
			addCriterion("created_on not between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andSectionIsNull() {
			addCriterion("section is null");
			return (Criteria) this;
		}

		public Criteria andSectionIsNotNull() {
			addCriterion("section is not null");
			return (Criteria) this;
		}

		public Criteria andSectionEqualTo(String value) {
			addCriterion("section =", value, "section");
			return (Criteria) this;
		}

		public Criteria andSectionNotEqualTo(String value) {
			addCriterion("section <>", value, "section");
			return (Criteria) this;
		}

		public Criteria andSectionGreaterThan(String value) {
			addCriterion("section >", value, "section");
			return (Criteria) this;
		}

		public Criteria andSectionGreaterThanOrEqualTo(String value) {
			addCriterion("section >=", value, "section");
			return (Criteria) this;
		}

		public Criteria andSectionLessThan(String value) {
			addCriterion("section <", value, "section");
			return (Criteria) this;
		}

		public Criteria andSectionLessThanOrEqualTo(String value) {
			addCriterion("section <=", value, "section");
			return (Criteria) this;
		}

		public Criteria andSectionLike(String value) {
			addCriterion("section like", value, "section");
			return (Criteria) this;
		}

		public Criteria andSectionNotLike(String value) {
			addCriterion("section not like", value, "section");
			return (Criteria) this;
		}

		public Criteria andSectionIn(List<String> values) {
			addCriterion("section in", values, "section");
			return (Criteria) this;
		}

		public Criteria andSectionNotIn(List<String> values) {
			addCriterion("section not in", values, "section");
			return (Criteria) this;
		}

		public Criteria andSectionBetween(String value1, String value2) {
			addCriterion("section between", value1, value2, "section");
			return (Criteria) this;
		}

		public Criteria andSectionNotBetween(String value1, String value2) {
			addCriterion("section not between", value1, value2, "section");
			return (Criteria) this;
		}

		public Criteria andSubjectIsNull() {
			addCriterion("subject is null");
			return (Criteria) this;
		}

		public Criteria andSubjectIsNotNull() {
			addCriterion("subject is not null");
			return (Criteria) this;
		}

		public Criteria andSubjectEqualTo(String value) {
			addCriterion("subject =", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotEqualTo(String value) {
			addCriterion("subject <>", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectGreaterThan(String value) {
			addCriterion("subject >", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectGreaterThanOrEqualTo(String value) {
			addCriterion("subject >=", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLessThan(String value) {
			addCriterion("subject <", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLessThanOrEqualTo(String value) {
			addCriterion("subject <=", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLike(String value) {
			addCriterion("subject like", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotLike(String value) {
			addCriterion("subject not like", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectIn(List<String> values) {
			addCriterion("subject in", values, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotIn(List<String> values) {
			addCriterion("subject not in", values, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectBetween(String value1, String value2) {
			addCriterion("subject between", value1, value2, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotBetween(String value1, String value2) {
			addCriterion("subject not between", value1, value2, "subject");
			return (Criteria) this;
		}

		public Criteria andDraftIsNull() {
			addCriterion("draft is null");
			return (Criteria) this;
		}

		public Criteria andDraftIsNotNull() {
			addCriterion("draft is not null");
			return (Criteria) this;
		}

		public Criteria andDraftEqualTo(Integer value) {
			addCriterion("draft =", value, "draft");
			return (Criteria) this;
		}

		public Criteria andDraftNotEqualTo(Integer value) {
			addCriterion("draft <>", value, "draft");
			return (Criteria) this;
		}

		public Criteria andDraftGreaterThan(Integer value) {
			addCriterion("draft >", value, "draft");
			return (Criteria) this;
		}

		public Criteria andDraftGreaterThanOrEqualTo(Integer value) {
			addCriterion("draft >=", value, "draft");
			return (Criteria) this;
		}

		public Criteria andDraftLessThan(Integer value) {
			addCriterion("draft <", value, "draft");
			return (Criteria) this;
		}

		public Criteria andDraftLessThanOrEqualTo(Integer value) {
			addCriterion("draft <=", value, "draft");
			return (Criteria) this;
		}

		public Criteria andDraftIn(List<Integer> values) {
			addCriterion("draft in", values, "draft");
			return (Criteria) this;
		}

		public Criteria andDraftNotIn(List<Integer> values) {
			addCriterion("draft not in", values, "draft");
			return (Criteria) this;
		}

		public Criteria andDraftBetween(Integer value1, Integer value2) {
			addCriterion("draft between", value1, value2, "draft");
			return (Criteria) this;
		}

		public Criteria andDraftNotBetween(Integer value1, Integer value2) {
			addCriterion("draft not between", value1, value2, "draft");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table post
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 23 16:16:26 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}