package com.dzx.app.entity;

public class Tag {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tag.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tag.name
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tag.id
	 * @return  the value of tag.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tag.id
	 * @param id  the value for tag.id
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tag.name
	 * @return  the value of tag.name
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tag.name
	 * @param name  the value for tag.name
	 * @mbg.generated  Wed Aug 23 16:32:34 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}
}