package com.dzx.app.mapper;

import com.dzx.app.entity.PostTagExample;
import com.dzx.app.entity.PostTagKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 23 16:32:34 CST 2017
     */
    long countByExample(PostTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 23 16:32:34 CST 2017
     */
    int deleteByExample(PostTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 23 16:32:34 CST 2017
     */
    int deleteByPrimaryKey(PostTagKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 23 16:32:34 CST 2017
     */
    int insert(PostTagKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 23 16:32:34 CST 2017
     */
    int insertSelective(PostTagKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 23 16:32:34 CST 2017
     */
    List<PostTagKey> selectByExample(PostTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 23 16:32:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") PostTagKey record, @Param("example") PostTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 23 16:32:34 CST 2017
     */
    int updateByExample(@Param("record") PostTagKey record, @Param("example") PostTagExample example);
}